import sqlite3

connection = sqlite3.connect("ALLDATA.db")
print("opened database.")
cursor = connection.cursor()

cursor.execute("DROP TABLE IF EXISTS kdrama")
cursor.execute("DROP TABLE IF EXISTS actor")
cursor.execute("DROP TABLE IF EXISTS genre")
cursor.execute("DROP TABLE IF EXISTS kdrama_genre")
cursor.execute("DROP TABLE IF EXISTS kdrama_actor")

'''
R 3.3 - select * from kdrama order by rating desc limit 20;

R 3.4 - select * from kdrama order by year desc limit 20;

R 3.5 - select kdrama.id,kdrama.title,kdrama.year,kdrama.rating from kdrama join kdrama_genre on kdrama.id = kdrama_genre.k_id join genre on genre.id = kdrama_genre.g_id where genre.name = "Crime";

R 3.6 - 1.  select * from kdrama where title like "%ordinary day%";

        2.  select actor.id,actor.name,actor.gender,actor.age from actor join kdrama_actor on actor.id = kdrama_actor.ac_id join kdrama on kdrama.id = kdrama_actor.k_id where kdrama.id = 27;
        
        3.  select kdrama.id,kdrama.title,kdrama.year,kdrama.rating,kdrama.numberOfEpisodes,kdrama.avgEpisodeLength from kdrama join kdrama_actor on kdrama.id = kdrama_actor.k_id join actor on actor.id = kdrama_actor.ac_id where actor.id = 46;

'''

# creating tables

kdrama = '''
CREATE TABLE kdrama (
    id INTEGER PRIMARY KEY NOT NULL,
    title TEXT,
    year INTEGER,
    rating REAL,
    numberOfEpisodes INTEGER,
    avgEpisodeLength INTEGER
)
'''
cursor.execute(kdrama)
print("created table kdrama.")


actor = '''
CREATE TABLE actor (
    id INTEGER PRIMARY KEY NOT NULL,
    name TEXT,
    gender TEXT,
    age INTEGER
)
'''
cursor.execute(actor)
print("created table actor.")


genre = '''
CREATE TABLE genre (
    id INTEGER PRIMARY KEY NOT NULL,
    name TEXT
)
'''
cursor.execute(genre)
print("created table genre.")


kdrama_genre = ''' 
CREATE TABLE kdrama_genre (
    id INTEGER PRIMARY KEY NOT NULL,
    k_id INTEGER,
    g_id INTEGER,
    FOREIGN KEY(k_id) REFERENCES kdrama(id),
    FOREIGN KEY(g_id) REFERENCES genre(id)
)
'''
cursor.execute(kdrama_genre)
print("created table kdrama_genre.")


kdrama_actor = '''
CREATE TABLE kdrama_actor (
    id INTEGER PRIMARY KEY NOT NULL,
    k_id INTEGER,
    ac_id INTEGER,
    FOREIGN KEY(k_id) REFERENCES kdrama(id),
    FOREIGN KEY(ac_id) REFERENCES actor(id)
)
'''
cursor.execute(kdrama_actor)
print("created table kdrama_actor.")



# inserting kdramas information

cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Move to Heaven', 2021, 9.2, 10, 52))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Flower of Evil', 2020, 9.1, 16, 70))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('My Mister', 2018, 9.1, 16, 77))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Prison Playbook', 2017, 9.1, 16, 92))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Mother', 2018, 9.0, 16, 63))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Crash Landing on You', 2019, 9.0, 16, 85))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Signal', 2016, 9.0, 16, 75))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Vincenzo', 2021, 9.0, 20, 85))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Kingdom: Season 2', 2020, 8.9, 6, 45))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Happiness', 2021, 8.9, 12, 65))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Healer', 2014, 8.9, 20, 60))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Stranger', 2017, 8.9, 16, 70))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('D.P.', 2021, 8.8, 6, 50))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Kingdom', 2019, 8.8, 6, 51))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('The Devil Judge', 2021, 8.8, 16, 70))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Mouse', 2021, 8.8, 20, 75))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('18 Again', 2020, 8.7, 16, 70))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Sweet Home', 2020, 8.7, 10, 52))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Defendant', 2017, 8.7, 18, 70))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Dear My Friends', 2016, 8.7, 16, 70))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('My Name', 2021, 8.7, 8, 50))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Live', 2018, 8.7, 18, 75))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Designated Survivor: 60 Days', 2019, 8.6, 16, 70))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('365: Repeat the Year', 2020, 8.6, 24, 35))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Squid Game', 2021, 8.6, 9, 60))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Vagabond', 2019, 8.5, 16, 70))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('One Ordinary Day', 2021, 8.5, 8, 70))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Circle', 2017, 8.5, 12, 60))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Extracurricular', 2020, 8.5, 10, 60))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Itaewon Class', 2020, 8.5, 16, 70))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('All of Us are Dead', 2022, 8.5, 12, 62))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Memorist', 2020, 8.4, 16, 65))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Her Private Life', 2019, 8.4, 16, 75))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('My Country: The New Age', 2019, 8.4, 16, 80))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('City Hunter', 2011, 8.4, 20, 70))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Liar Game', 2014, 8.3, 12, 63))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Confession', 2019, 8.3, 16, 60))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('A Korean Odyssey', 2017, 8.3, 20, 80))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Vampire Prosecutor', 2011, 8.2, 12, 58))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('The Silent Sea', 2021, 8.2, 8, 50))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Suits', 2018, 8.2, 16, 60))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Start-Up', 2020, 8.1, 16, 85))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Argon', 2017, 8.0, 8, 70))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Chief of Staff', 2019, 8.0, 10, 66))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Goblin', 2016, 8.8, 16, 82))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Suspicious Partner', 2017, 8.3, 40, 30))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Because This Is My First Life', 2017, 8.5, 16, 70))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('He is Pyschometric', 2019, 8.4, 16, 64))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Are You Human Too?', 2018, 8.3, 36, 35))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('The Uncanny Counter', 2020, 8.8, 16, 70))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Save Me', 2017, 8.6, 16, 60))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Search: WWW', 2019, 8.5, 16, 70))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Hospital Playlist', 2020, 9.1, 12, 90))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Hospital Playlist 2', 2021, 9.1, 12, 100))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('SKY Castle', 2018, 8.9, 20, 75))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Hometown Cha-Cha-Cha', 2021, 8.8, 16, 80))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('The Penthouse: War in Life', 2020, 8.8, 21, 85))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Taxi Driver', 2021, 8.8, 16, 65))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Beyond Evil', 2021, 8.8, 16, 65))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('The Penthouse 2: War in Life', 2021, 8.8, 13, 75))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('The Guest', 2018, 8.7, 16, 67))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Chicago Typewriter', 2017, 8.7, 16, 70))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Misaeng: Incomplete Life', 2014, 8.7, 20, 80))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('The Fiery Priest', 2019, 8.7, 40, 35))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Hotel del Luna', 2019, 8.7, 16, 80))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Hot Stove League', 2019, 8.7, 16, 62))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Law School', 2021, 8.7, 16, 65))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Stranger 2', 2020, 8.6, 16, 62))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Once Again', 2020, 8.6, 100, 35))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Avengers Social Club', 2017, 8.6, 12, 60))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Nobody Knows', 2020, 8.5, 16, 70))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('I Hear Your Voice', 2013, 8.5, 18, 60))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Beautiful World', 2019, 8.5, 16, 60))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Kairos', 2020, 8.5, 16, 70))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('W', 2016, 8.5, 16, 60))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Mad for Each Other', 2021, 8.5, 13, 35))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('The World of the Married', 2020, 8.5, 16, 80))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Voice', 2017, 8.5, 16, 60))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('I''m Not a Robot', 2017, 8.4, 32, 35))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Work Later, Drink Now', 2021, 8.4, 12, 35))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Moon Embracing the Sun', 2012, 8.4, 20, 65))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Mr. Queen', 2020, 9.0, 20, 80))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Mr. Sunshine', 2018, 8.9, 24, 80))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('My Unfamiliar Family', 2020, 8.4, 16, 75))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('The Crowned Clown', 2019, 8.4, 16, 80))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Lost', 2021, 8.4, 16, 70))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Twenty-Five Twenty-One', 2022, 8.7, 16, 70))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Racket Boys', 2021, 8.8, 16, 75))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Weightlifting Fairy Kim Bok Joo', 2016, 8.8, 16, 60))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Two Weeks', 2013, 8.5, 16, 65))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('School 2013', 2012, 8.2, 16, 65))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('History of the Salaryman', 2012, 8.2, 22, 65))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Solomon''s Perjury', 2016, 8.2, 12, 60))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Class of Lies', 2019, 8.4, 16, 70))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Sell Your Haunted House', 2021, 8.4, 16, 70))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Zombie Detective', 2020, 8.3, 24, 30))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Uncle', 2021, 8.1, 16, 70))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Thirty But Seventeen', 2018, 8.5, 32, 35))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Run On', 2020, 8.4, 16, 70))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Lie After Lie', 2020, 8.3, 16, 69))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Psychopath Diary', 2019, 8.3, 16, 80))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Ghost Doctor', 2022, 8.6, 16, 70))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Dr. Romantic', 2016, 8.7, 20, 60))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('Nightmare Teacher', 2016, 7.6, 12, 15))
cursor.execute("INSERT INTO kdrama (title,year,rating,numberOfEpisodes,avgEpisodeLength) VALUES (?,?,?,?,?)", ('It''s Okay to Not Be Okay', 2020, 9.0, 16, 75))



# inserting genres information

cursor.execute("INSERT INTO genre (name) VALUES ('Life')")
cursor.execute("INSERT INTO genre (name) VALUES ('Drama')")
cursor.execute("INSERT INTO genre (name) VALUES ('Family')")
cursor.execute("INSERT INTO genre (name) VALUES ('Thriller')")
cursor.execute("INSERT INTO genre (name) VALUES ('Romance')")
cursor.execute("INSERT INTO genre (name) VALUES ('Crime')")
cursor.execute("INSERT INTO genre (name) VALUES ('Melodrama')")
cursor.execute("INSERT INTO genre (name) VALUES ('Psychological')")
cursor.execute("INSERT INTO genre (name) VALUES ('Comedy')")
cursor.execute("INSERT INTO genre (name) VALUES ('Military')")
cursor.execute("INSERT INTO genre (name) VALUES ('Political')")
cursor.execute("INSERT INTO genre (name) VALUES ('Mystery')")
cursor.execute("INSERT INTO genre (name) VALUES ('Sci-Fi')")
cursor.execute("INSERT INTO genre (name) VALUES ('Law')")
cursor.execute("INSERT INTO genre (name) VALUES ('Historical')")
cursor.execute("INSERT INTO genre (name) VALUES ('Horror')")
cursor.execute("INSERT INTO genre (name) VALUES ('Supernatural')")
cursor.execute("INSERT INTO genre (name) VALUES ('Action')")
cursor.execute("INSERT INTO genre (name) VALUES ('Fantasy')")
cursor.execute("INSERT INTO genre (name) VALUES ('School')")
cursor.execute("INSERT INTO genre (name) VALUES ('Youth')")
cursor.execute("INSERT INTO genre (name) VALUES ('Business')")
cursor.execute("INSERT INTO genre (name) VALUES ('Friendship')")
cursor.execute("INSERT INTO genre (name) VALUES ('Medical')")
cursor.execute("INSERT INTO genre (name) VALUES ('Sports')")
cursor.execute("INSERT INTO genre (name) VALUES ('Music')")



# inserting actors information 

cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Lee Je Hoon','Male',37))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Tang Jun Sang','Male',18))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Lee Joon Gi','Male',39))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Moon Chae Won','Female',35))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Lee Sun Kyun','Male',46))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('IU','Female',28))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Park Hae Soo','Male',40))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Jung Kyung Ho','Male',38))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Lee Bo Young','Female',43))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Heo Yool','Female',12))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Hyun Bin','Male',39))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Son Ye Jin','Female',40))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Kim Hye Soo','Female',51))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Song Joong Ki','Male',36))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Jeon Yeo Been','Female',32))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Joo Ji Hoon','Male',39))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Bae Doo Na','Female',42))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Han Hyo Joo','Female',35))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Park Hyung Sik','Male',30))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Ji Chang Wook','Male',34))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Park Min Young','Female',35))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Jo Seung Woo','Male',41))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Jung Hae In','Male',33))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Koo Kyo Hwan','Male',39))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Ji Sung','Male',44))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Kim Min Jung','Female',39))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Lee Seung Gi','Male',35))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Lee Hee Joon','Male',42))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Kim Ha Neul','Female',44))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Yoon Sang Hyun','Male',48))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Song Kang','Male',27))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Lee Jin Wook','Male',40))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Uhm Ki Joon','Male',45))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Go Hyun Jung','Female',50))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Kim Hye Ja','Female',80))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Han So Hee','Female',27))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Park Hee Soon','Male',52))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Lee Kwang Soo','Male',36))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Jung Yu Mi','Female',39))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Ji Jin Hee','Male',50))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Son Seok Koo','Male',39))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Lee Joon Hyuk','Male',37))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Nam Ji Hyun','Female',26))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Lee Jung Jae','Male',48))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Bae Suzy','Female',27))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Kim Soo Hyun','Male',34))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Cha Seung Won','Male',51))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Yeo Jin Goo','Male',24))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Kim Kang Woo','Male',43))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Kim Dong Hee','Male',22))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Park Joo Hyun','Female',27))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Park Seo Joon','Male',33))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Kim Da Mi','Female',26))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Yoon Chan Young','Male',20))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Park Ji Hoo','Female',18))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Yoo Seung Ho','Male',28))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Lee Se Young','Female',29))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Kim Jae Wook','Male',38))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Yang Se Jong','Male',29))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Woo Do Hwan','Male',29))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Lee Min Ho','Male',34))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Lee Sang Yoon','Male',40))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Shin Sung Rok','Male',39))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Lee Jun Ho','Male',32))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Shin Hyun Bin','Female',35))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Oh Yeon Seo','Female',34))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Yeon Jung Hoon','Male',43))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Lee Young Ah','Female',37))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Gong Yoo','Male',42))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Jang Dong Gun','Male',49))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Nam Joo Hyuk','Male',28))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Kim Joo Hyuk','Male',45))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Chun Woo Hee','Female',34))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Shin Min Ah','Female',37))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Kim Go Eun','Female',30))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Jung So Min','Female',32))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Lee Min Ki','Male',37))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Park Jin Young','Male',27))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Shin Ye Eun','Female',24))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Seo Kang Joon','Male',28))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Gong Seung Yeon','Female',28))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Cho Byeong Kyu','Male',25))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Yoo Joon Sang','Male',52))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Seo Yea Ji','Female',31))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Im Soo Jung','Female',42))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Lee Da Hee','Female',36))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Jo Jung Suk','Male',41))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Yoo Yeon Seok','Male',37))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Yeom Jung Ah','Female',49))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Lee Tae Ran','Female',46))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Kim Seon Ho','Male',35))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Kim So Yeon','Female',41))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Eugene','Female',40))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Esom','Female',32))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Shin Ha Kyun','Male',47))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Kim Dong Wook','Male',38))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Yoo Ah In','Male',35))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Im Si Wan','Male',33))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Lee Sung Min','Male',53))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Kim Nam Gil','Male',41))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Kim Sung Kyun','Male',41))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Namkoong Min','Male',43))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Park Eun Bin','Female',29))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Kim Myung Min','Male',49))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Kim Bum','Male',32))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Chun Ho Jin','Male',61))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Cha Hwa Yun','Female',61))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Lee Yo Won','Female',41))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Ra Mi Ran','Female',46))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Kim Seo Hyung','Female',48))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Ryu Deok Hwan','Male',34))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Lee Jong Suk','Male',32))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Choo Ja Hyun','Female',43))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Jung Woo','Male',41))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Kim Hee Ae','Female',54))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Park Hae Joon','Male',45))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Jang Hyuk','Male',45))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Lee Ha Na','Female',39))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Chae Soo Bin','Female',27))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Lee Sun Bin','Female',28))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Han Sun Hwa','Female',31))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Han Ga In','Female',40))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Shin Hye Sun','Female',32))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Kim Jung Hyun','Male',31))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Lee Byung Hun','Male',51))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Han Ye Ri','Female',37))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Kim Ji Suk','Male',40))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Jeon Do Yeon','Female',49))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Ryu Jeon Yeol','Male',35))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Kim Tae Ri','Female',31))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Lee Yong Dae','Male',33))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Jang Sung Kyu','Male',38))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Lee Sung Kyung','Female',31))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Park Ha Sun','Female',34))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Kim Woo Bin','Male',32))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Lee Bum Soo','Male',52))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Jung Gyu Woon','Male',39))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Kim Hyun Soo','Female',21))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Jang Dong Yoon','Male',29))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Yoon Kyun Sang','Male',34))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Geum Sae Rok','Female',29))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Jang Na Ra','Female',40))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Jung Yong Hwa','Male',32))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Choi Jin Hyuk','Male',36))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Oh Jung Se','Male',44))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Jeon Hye Jin','Female',46))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Shin Se Kyung','Female',31))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Lee Yoo Ri','Female',42))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Yoon Shi Yoon','Male',35))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Jung In Sun','Female',30))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Rain','Male',39))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Han Seok Kyu','Male',57))
cursor.execute("INSERT INTO actor (name,gender,age) VALUES (?,?,?)", ('Kim So Hyun','Female',22))


# inserting kdrama_genre information

cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (1,1))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (1,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (1,3))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (2,4))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (2,5))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (2,6))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (2,7))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (3,8))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (3,1))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (3,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (3,3))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (4,9))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (4,6))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (4,1))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (4,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (5,4))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (5,12))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (5,8))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (5,7))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (6,10))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (6,9))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (6,5))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (6,11))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (7,4))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (7,12))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (7,13))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (8,9))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (8,14))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (8,6))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (8,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (9,4))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (9,15))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (9,16))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (9,17))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (10,18))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (10,4))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (10,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (10,19))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (11,18))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (11,4))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (11,12))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (11,5))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (12,4))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (12,12))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (12,14))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (12,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (13,18))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (13,10))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (13,9))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (13,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (14,4))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (14,15))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (14,16))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (14,11))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (15,12))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (15,14))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (15,6))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (15,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (16,4))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (16,12))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (16,8))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (16,13))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (17,5))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (17,1))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (17,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (17,19))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (18,16))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (18,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (18,13))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (18,17))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (19,4))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (19,12))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (19,14))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (19,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (20,1))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (20,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (20,3))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (20,7))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (21,18))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (21,4))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (21,12))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (21,6))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (22,9))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (22,5))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (22,6))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (22,1))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (23,4))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (23,12))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (23,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (23,11))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (24,4))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (24,12))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (24,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (24,19))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (25,18))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (25,4))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (25,12))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (25,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (26,18))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (26,4))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (26,12))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (26,6))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (27,4))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (27,12))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (27,14))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (27,6))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (28,4))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (28,12))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (28,13))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (29,8))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (29,20))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (29,21))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (30,22))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (30,5))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (30,1))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (30,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (31,18))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (31,4))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (31,16))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (31,13))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (32,18))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (32,4))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (32,12))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (32,17))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (33,9))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (33,5))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (34,18))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (34,15))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (34,5))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (34,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (35,18))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (35,4))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (35,6))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (36,4))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (36,12))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (36,8))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (36,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (37,4))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (37,12))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (37,14))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (37,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (38,16))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (38,9))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (38,5))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (38,19))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (39,18))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (39,12))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (39,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (39,17))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (40,4))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (40,12))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (40,16))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (40,13))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (41,18))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (41,22))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (41,14))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (41,1))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (41,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (42,22))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (42,9))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (42,5))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (42,21))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (43,12))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (43,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (43,11))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (44,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (44,11))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (45,9))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (45,5))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (45,19))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (45,7))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (46,4))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (46,9))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (46,14))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (46,5))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (47,9))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (47,5))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (47,1))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (47,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (48,4))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (48,12))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (48,5))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (48,17))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (49,9))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (49,5))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (49,13))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (49,19))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (50,18))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (50,12))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (50,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (50,17))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (51,18))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (51,4))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (51,12))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (51,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (52,22))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (52,9))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (52,5))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (52,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (53,23))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (53,5))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (53,1))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (53,24))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (54,23))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (54,5))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (54,1))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (54,24))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (55,12))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (55,8))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (55,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (55,3))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (56,9))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (56,5))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (56,1))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (56,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (57,4))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (57,12))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (57,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (57,3))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (58,18))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (58,4))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (58,12))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (58,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (59,4))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (59,18))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (59,8))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (59,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (60,4))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (60,12))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (60,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (60,3))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (61,4))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (61,12))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (61,16))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (61,17))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (62,9))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (62,5))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (62,17))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (62,11))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (63,23))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (63,22))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (63,1))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (63,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (64,18))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (64,12))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (64,9))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (64,6))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (65,16))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (65,9))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (65,5))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (65,19))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (66,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (66,25))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (66,7))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (67,12))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (67,14))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (67,6))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (67,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (68,4))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (68,12))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (68,14))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (68,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (69,9))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (69,5))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (69,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (69,3))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (70,23))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (70,9))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (70,1))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (70,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (71,4))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (71,12))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (71,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (71,7))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (72,12))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (72,14))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (72,5))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (72,17))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (73,1))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (73,20))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (73,3))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (73,7))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (74,18))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (74,4))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (74,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (74,13))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (75,4))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (75,9))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (75,5))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (75,19))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (76,9))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (76,5))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (76,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (77,4))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (77,5))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (77,3))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (77,7))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (78,4))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (78,12))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (78,8))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (79,9))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (79,5))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (79,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (79,13))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (80,23))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (80,9))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (80,1))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (80,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (81,15))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (81,5))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (81,17))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (81,11))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (82,15))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (82,9))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (82,5))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (82,19))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (83,10))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (83,15))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (83,5))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (83,7))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (84,1))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (84,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (84,3))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (85,15))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (85,5))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (85,7))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (85,11))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (86,1))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (86,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (86,7))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (87,5))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (87,1))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (87,21))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (87,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (88,25))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (89,9))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (89,5))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (89,21))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (89,25))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (90,18))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (90,4))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (90,12))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (90,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (91,23))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (91,20))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (91,21))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (91,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (92,12))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (92,9))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (92,7))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (92,11))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (93,23))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (93,14))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (93,20))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (93,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (94,4))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (94,12))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (94,14))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (94,21))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (95,4))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (95,12))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (95,9))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (95,19))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (96,4))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (96,12))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (96,9))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (96,19))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (97,26))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (97,9))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (97,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (97,3))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (98,26))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (98,12))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (98,9))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (98,5))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (99,5))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (99,1))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (99,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (99,25))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (100,4))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (100,5))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (100,7))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (101,4))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (101,12))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (101,9))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (101,6))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (102,9))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (102,24))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (102,19))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (102,17))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (103,5))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (103,2))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (103,24))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (104,12))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (104,16))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (104,21))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (104,17))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (105,8))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (105,9))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (105,5))
cursor.execute("INSERT INTO kdrama_genre (k_id,g_id) VALUES (?,?)", (105,2))



# inserting kdrama_actor information

cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (1,1))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (1,2))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (2,3))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (2,4))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (3,5))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (3,6))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (4,7))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (4,8))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (5,9))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (5,10))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (6,11))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (6,12))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (7,1))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (7,13))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (8,14))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (8,15))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (9,16))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (9,17))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (10,18))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (10,19))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (11,20))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (11,21))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (12,22))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (12,17))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (13,23))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (13,24))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (14,16))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (14,17))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (15,25))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (15,26))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (16,27))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (16,28))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (17,29))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (17,30))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (18,31))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (18,32))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (19,25))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (19,33))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (20,34))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (20,35))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (21,36))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (21,37))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (22,38))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (22,39))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (23,40))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (23,41))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (24,42))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (24,43))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (25,44))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (25,7))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (26,27))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (26,45))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (27,46))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (27,47))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (28,48))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (28,49))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (29,50))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (29,51))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (30,52))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (30,53))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (31,54))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (31,55))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (32,56))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (32,57))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (33,21))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (33,58))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (34,59))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (34,60))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (35,61))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (35,21))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (36,62))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (36,63))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (37,64))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (37,65))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (38,27))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (38,66))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (39,67))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (39,68))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (40,17))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (40,69))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (41,70))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (41,19))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (42,45))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (42,71))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (43,72))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (43,73))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (44,44))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (44,74))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (45,69))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (45,75))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (46,20))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (46,43))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (47,76))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (47,77))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (48,78))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (48,79))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (49,80))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (49,81))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (50,82))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (50,83))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (51,84))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (51,60))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (52,85))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (52,86))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (53,87))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (53,88))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (54,87))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (54,88))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (55,89))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (55,90))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (56,74))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (56,91))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (57,92))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (57,93))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (58,1))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (58,94))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (59,95))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (59,48))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (60,92))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (60,93))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (61,96))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (61,58))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (62,97))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (62,85))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (63,98))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (63,99))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (64,100))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (64,101))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (65,6))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (65,48))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (66,102))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (66,103))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (67,104))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (67,105))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (68,22))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (68,17))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (69,106))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (69,107))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (70,108))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (70,109))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (71,110))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (71,111))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (72,112))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (72,9))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (73,37))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (73,113))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (74,63))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (74,57))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (75,18))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (75,112))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (76,66))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (76,114))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (77,115))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (77,116))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (78,117))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (78,118))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (79,56))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (79,119))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (80,120))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (80,121))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (81,122))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (81,46))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (82,123))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (82,124))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (83,125))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (83,130))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (84,126))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (84,127))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (85,48))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (85,57))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (86,128))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (86,129))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (87,130))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (87,71))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (88,131))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (88,132))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (89,133))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (89,71))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (90,3))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (90,134))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (91,112))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (91,135))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (92,136))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (92,137))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (93,138))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (93,139))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (94,140))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (94,141))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (95,142))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (95,143))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (96,144))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (96,51))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (97,145))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (97,146))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (98,123))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (98,59))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (99,98))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (99,147))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (100,148))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (100,67))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (101,149))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (101,150))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (102,151))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (102,105))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (103,152))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (103,88))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (104,153))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (104,33))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (105,46))
cursor.execute("INSERT INTO kdrama_actor (k_id,ac_id) VALUES (?,?)", (105,84))




print("all tables data inserted.")




'''
Move to Heaven                      life,drama,family                   Lee Je Hoon (M,37), Tang Jun Sang (M,18)
Flower of Evil                      thriller,romance,crime,melodrama                    Lee Joon Gi (M,39), Moon Chae Won (F,35)
My Mister                       psychological,life,drama,family                         Lee Sun Kyun (M,46), IU (F,28)
Prison Playbook                         comedy,crime,life,drama                     Park Hae Soo (M,40), Jung Kyung Ho (M,38) 
Mother                      thriller,mystery,psychological,melodrama                    Lee Bo Young (F,43), Heo Yool (F,12)
Crash Landing on You                        military,comedy,romance,political                       Hyun Bin (M,39), Son Ye Jin (F,40)
Signal                      thriller,mystery,sci-fi                     Lee Je Hoon (M,37), Kim Hye Soo (F,51)
Vincenzo                        comedy,law,crime,drama                      Song Joong Ki (M,36), Jeon Yeo Been (F,32)
Kingdom: Season 2                       thriller,historical,horror,supernatural                         Joo Ji Hoon (M,39), Bae Doo Na (F,42)
Happiness                       action,thriller,drama,fantasy                       Han Hyo Joo (F,35), Park Hyung Sik (M,30)
Healer                      action,thriller,mystery,romance                     Ji Chang Wook (M,34), Park Min Young (F,35)
Stranger                        thriller,mystery,law,drama                      Jo Seung Woo (M,41), Bae Doo Na (F,42)
D.P.                        action,military,comedy,drama                        Jung Hae In (M,33), Koo Kyo Hwan (M,39)
Kingdom                         thriller,historical,horror,political                    Joo Ji Hoon (M,39), Bae Doo Na (F,42)
The Devil Judge                         mystery,law,crime,drama                     Ji Sung (M,44), Kim Min Jung (F,39)
Mouse                       thriller,mystery,psychological,sci-fi                       Lee Seung Gi (M,35), Lee Hee Joon (M,42)
18 Again                        romance,life,drama,fantasy                      Kim Ha Neul (F,44), Yoon Sang Hyun (M,48)
Sweet Home                      horror,drama,sci-fi,supernatural                    Song Kang (M,27), Lee Jin Wook (M,40)
Defendant                       thriller,mystery,law,drama                      Ji Sung (M,44), Uhm Ki Joon (M,45)
Dear My Friends                         life,drama,family,melodrama                     Go Hyun Jung (F,50), Kim Hye Ja (F,80)
My Name                         action,thriller,mystery,crime                       Han So Hee (F,27), Park Hee Soon (M,52)
Live                        comedy,romance,crime,life                       Lee Kwang Soo (M,36), Jung Yu Mi (F,39)
Designated Survivor: 60 Days                        thriller,mystery,drama,political                        Ji Jin Hee (M,50), Son Seok Koo (M,39)
365: Repeat the Year                        thriller,mystery,drama,fantasy                      Lee Joon Hyuk (M,37), Nam Ji Hyun (F,26)
Squid Game                      action,thriller,mystery,drama                   Lee Jung Jae (M,48), Park Hae Soo (M,40)
Vagabond                        action,thriller,mystery,crime                       Lee Seung Gi (M,35), Bae Suzy (F,27)
One Ordinary Day                        thriller,mystery,law,crime                      Kim Soo Hyun (M,34), Cha Seung Won (M,51)
Circle                      thriller,mystery,sci-fi                     Yeo Jin Goo (M,24), Kim Kang Woo (M,43)
Extracurricular                         psychological,school,youth                      Kim Dong Hee (M,22), Park Joo Hyun (F,27)
Itaewon Class                       business,romance,life,drama                         Park Seo Joon (M,33), Kim Da Mi (F,26)
All of Us are Dead                      action,thriller,horror,sci-fi                   Yoon Chan Young (M,20), Park Ji Hoo (F,18)
Memorist                        action,thriller,mystery,supernatural                        Yoo Seung Ho (M,28), Lee Se Young (F,29)
Her Private Life                        comedy,romance                      Park Min Young (F,35), Kim Jae Wook (M,38) 
My Country: The New Age                         action,historical,romance,drama                     Yang Se Jong (M,29), Woo Do Hwan (M,29)
City Hunter                         action,thriller,crime                       Lee Min Ho (M,34), Park Min Young (F,35)
Liar Game                       thriller,mystery,psychological,drama                        Lee Sang Yoon (M,40), Shin Sung Rok (M,39)
Confession                      thriller,mystery,law,drama                      Lee Jun Ho (M,32), Shin Hyun Bin (F,35)
A Korean Odyssey                        horror,comedy,romance,fantasy                       Lee Seung Gi (M,35), Oh Yeon Seo (F,34)
Vampire Prosecutor                      action,mystery,drama,supernatural                   Yeon Jung Hoon (M,43), Lee Young Ah (F,37)
The Silent Sea                      thriller,mystery,horror,sci-fi                      Bae Doo Na (F,42), Gong Yoo (M,42)
Suits                       action,business,law,life,drama                      Jang Dong Gun (M,49), Park Hyung Sik (M,30)
Start-Up                        business,comedy,romance,youth                       Bae Suzy (F,27), Nam Joo Hyuk (M,28)
Argon                       mystery,drama,political                         Kim Joo Hyuk (M,45), Chun Woo Hee (F,34)
Chief of Staff                      drama,political                     Lee Jung Jae (M,48), Shin Min Ah (F,37)
Goblin                      comedy,romance,fantasy,melodrama                    Gong Yoo (M,42), Kim Go Eun (F,30)
Suspicious Partner                      thriller,comedy,law,romance                     Ji Chang Wook (M,34), Nam Ji Hyun (F,26)
Because This Is My First Life                       comedy,romance,life,drama                       Jung So Min (F,32), Lee Min Ki (M,37)
He is Pyschometric                      thriller,mystery,romance,supernatural                   Park Jin Young (M,27), Shin Ye Eun (F,24)
Are You Human Too?                      comedy,romance,sci-fi,fantasy                   Seo Kang Joon (M,28), Gong Seung Yeon (F,28)
The Uncanny Counter                         action,mystery,drama,supernatural                       Cho Byeong Kyu (M,25), Yoo Joon Sang (M,52)
Save Me                         action,thriller,mystery,drama                       Seo Yea Ji (F,31), Woo Do Hwan (M,29)
Search: WWW                         business,comedy,romance,drama                       Im Soo Jung (F,42), Lee Da Hee (F,36)
Hospital Playlist                       friendship,romance,life,medical                         Jo Jung Suk (M,41), Yoo Yeon Seok (M,37)
Hospital Playlist 2                         friendship,romance,life,medical                     Jo Jung Suk (M,41), Yoo Yeon Seok (M,37)
SKY Castle                      mystery,psychological,drama,family                      Yeom Jung Ah (F,49), Lee Tae Ran (F,46)
Hometown Cha-Cha-Cha                        comedy,romance,life,drama                       Shin Min Ah (F,37), Kim Seon Ho (M,35)
The Penthouse: War in Life                      thriller,mystery,drama,family                   Kim So Yeon (F,41), Eugene (F,40)
Taxi Driver                         action,thriller,mystery,drama                       Lee Je Hoon (M,37), Esom (F,32)
Beyond Evil                         thriller,mystery,psychological,drama                    Shin Ha Kyun (M,47), Yeo Jin Goo (M,24)
The Penthouse 2: War in Life                        thriller,mystery,drama,family                       Kim So Yeon (F,41), Eugene (F,40)
The Guest                       thriller,mystery,horror,supernatural                        Kim Dong Wook (M,38), Kim Jae Wook (M,38)
Chicago Typewriter                      comedy,romance,supernatural,political                   Yoo Ah In (M,35), Im Soo Jung (F,42)
Misaeng: Incomplete Life                        friendship,business,life,drama                      Im Si Wan (M,33), Lee Sung Min (M,53)
The Fiery Priest                        action,mystery,comedy,crime                     Kim Nam Gil (M,41), Kim Sung Kyun (M,41)
Hotel del Luna                      horror,comedy,romance,fantasy                   IU (F,28), Yeo Jin Goo (M,24)
Hot Stove League                        drama,sports,melodrama                      Namkoong Min (M,43), Park Eun Bin (F,29)
Law School                      mystery,law,crime,drama                     Kim Myung Min (M,49), Kim Bum (M,32)
Stranger 2                      thriller,mystery,law,drama                      Jo Seung Woo (M,41), Bae Doo Na (F,42)
Once Again                      comedy,romance,drama,family                     Chun Ho Jin (M,61), Cha Hwa Yun (F,61)
Avengers Social Club                        friendship,comedy,life,drama                        Lee Yo Won (F,41), Ra Mi Ran (F,46)
Nobody Knows                        thriller,mystery,drama,melodrama                        Kim Seo Hyung (F,48), Ryu Deok Hwan (M,34)
I Hear Your Voice                       mystery,law,romance,supernatural                        Lee Jong Suk (M,32), Lee Bo Young (F,43)
Beautiful World                         life,school,family,melodrama                    Park Hee Soon (M,52), Choo Ja Hyun (F,43)
Kairos                      action,thriller,drama,sci-fi                    Shin Sung Rok (M,39), Lee Se Young (F,29)
W                       thriller,comedy,romance,fantasy                         Han Hyo Joo (F,35), Lee Jong Suk (M,32)
Mad for Each Other                      comedy,romance,drama                    Oh Yeon Seo (F,34), Jung Woo (M,41) 
The World of the Married                        thriller,romance,family,melodrama                       Kim Hee Ae (F,54), Park Hae Joon (M,45)
Voice                       thriller,mystery,psychological                      Jang Hyuk (M,45), Lee Ha Na (F,39)
Im Not a Robot                      comedy,romance,drama,sci-fi                     Yoo Seung Ho (M,28), Chae Soo Bin (F,27)
Work Later, Drink Now                       friendship,comedy,life,drama                        Lee Sun Bin (F,28), Han Sun Hwa (F,31)
Moon Embracing the Sun                      historical,romance,supernatural,political                   Han Ga In (F,40), Kim Soo Hyun (M,34)
Mr. Queen                       historical,comedy,romance,fantasy                       Shin Hye Sun (F,32), Kim Jung Hyun (M,31)
Mr. Sunshine                        military,historical,romance,melodrama                       Lee Byung Hun (M,51), Kim Tae Ri (F,31)
My Unfamiliar Family                        life,drama,family                       Han Ye Ri (F,37), Kim Ji Suk (M,40)
The Crowned Clown                       historical,romance,melodrama,political                      Yeo Jin Goo (M,24), Lee Se Young (F,29) 
Lost                        life,drama,melodrama                        Jeon Do Yeon (F,49), Ryu Jeon Yeol (M,35)
Twenty-Five Twenty-One                      romance,life,youth,drama                    Kim Tae Ri (F,31), Nam Joo Hyuk (M,28)
Racket Boys                         sports                      Lee Yong Dae (M,33), Jang Sung Kyu (M,38)
Weightlifting Fairy Kim Bok Joo                         comedy,romance,youth,sports                     Lee Sung Kyung (F,31), Nam Joo Hyuk (M,28)
Two Weeks                       action,thriller,mystery,drama                       Lee Joon Gi (M,39), Park Ha Sun (F,34)
School 2013                         friendship,school,youth,drama                       Lee Jong Suk (M,32), Kim Woo Bin (M,32)
History of the Salaryman                        mystery,comedy,melodrama,political                      Lee Bum Soo (M,52), Jung Gyu Woon (M,39)
Solomons Perjury                        friendship,law,school,drama                     Kim Hyun Soo (F,21), Jang Dong Yoon (M,29)
Class of Lies                       thriller,mystery,law,youth                      Yoon Kyun Sang (M,34), Geum Sae Rok (F,29)
Sell Your Haunted House                         thriller,mystery,comedy,fantasy                     Jang Na Ra (F,40), Jung Yong Hwa (M,32)
Zombie Detective                        thriller,mystery,comedy,fantasy                     Choi Jin Hyuk (M,36), Park Joo Hyun (F,27)
Uncle                       music,comedy,drama,family                       Oh Jung Se (M,44), Jeon Hye Jin (F,46)
Thirty But Seventeen                        music,mystery,comedy,romance                        Shin Hye Sun (F,32), Yang Se Jong (M,29)
Run On                      romance,life,drama,sports                   Im Si Wan (M,33), Shin Se Kyung (F,31)
Lie After Lie                       thriller,romance,melodrama                      Lee Yoo Ri (F,42), Yeon Jung Hoon (M,43)
Psychopath Diary                        thriller,mystery,comedy,crime                       Yoon Shi Yoon (M,35), Jung In Sun (F,30)
Ghost Doctor                        comedy,medical,fantasy,supernatural                     Rain (M,39), Kim Bum (M,32)
Dr. Romantic                        romance,drama,medical                       Han Seok Kyu (M,57), Yoo Yeon Seok (M,37) 
Nightmare Teacher                       mystery,horror,youth,supernatural                       Kim So Hyun (F,22), Uhm Ki Joon (M,45)
It's Okay to Not Be Okay                        psychological,comedy,romance,drama                      Kim Soo Hyun (M,34), Seo Yea Ji (F,31)
'''





connection.commit()
connection.close()